name: KDebugger Ready

on:
  push:
    branches:
      - master

jobs:
  replace_namespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace Namespace
        run: |
          git checkout master
          find . -type f -name '*.cs' -exec sed -i 's/namespace ShizoGames/namespace KDebugger.Plugins.ShizoGames/g' {} +
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -a -m "KDebugger Ready"
          git branch -D kdbg
          git checkout -b kdbg
          git push --set-upstream origin kdbg
