name: KDebugger Ready

on:
  push:
    branches:
      - master

jobs:
  update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Existing Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push origin --delete kdbg || echo "Branch 'kdbg' does not exist"

      - name: Create Branch
        run: |
          git checkout -b kdbg

      - name: Update Namespaces
        run: |
          find . -type f -name '*.cs' -exec sed -i 's/namespace ShizoGames/namespace KDebugger.Plugins.ShizoGames/g' {} +

      - name: Update Runtime Asmdef
        run: |
          find . -type f -regex '.*/ShizoGames\.\(?!.*\.Editor\)\(.*\)\.asmdef' -exec bash -c 'mv "$0" "${0/ShizoGames.\(?!.*\.Editor\)\(.*\).asmdef/KDebugger.Plugins.Reference.asmref}"' {} +
          find . -type f -name 'KDebugger.Plugins.Reference.asmref' -exec bash -c 'echo "{\n    \"reference\": \"KDebugger.Plugins\"\n}" > "$0"' {} +
          
      - name: Update Editor Asmdef
        run: |
          find . -type f -regex '.*/ShizoGames\.\(.*\)\.Editor.asmdef' -exec bash -c 'mv "$0" "${0/ShizoGames.\(.*\)\.Editor.asmdef/KDebugger.Plugins.Editor.Reference.asmdef}"' {} +
          find . -type f -name 'KDebugger.Plugins.Editor.Reference.asmref' -exec bash -c 'echo "{\n    \"reference\": \"KDebugger.Plugins.Editor\"\n}" > "$0"' {} +

      - name: Push Branch
        run: |
          git add .
          git commit -m "KDebugger Ready"
          git push origin kdbg
