name: KDebugger Ready

on:
  push:
    branches:
      - master

jobs:
  update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Existing Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push origin --delete kdbg || echo "Branch 'kdbg' does not exist"

      - name: Create Branch
        run: |
          git checkout -b kdbg

      - name: Update Namespaces
        run: |
          find . -type f -name '*.cs' -exec sed -i 's/namespace ShizoGames/namespace KDebugger.Plugins.ShizoGames/g' {} +

      - name: Replace Editor Files
        run: |
          find . -type f -name 'ShizoGames.*.Editor.asmdef' -exec bash -c 'mv "$0" "${0/\.Editor\.asmdef/.Editor.References.asmref}"' {} +
          find . -type f -name 'KDebugger.Plugins.*.Editor.References.asmref' -exec bash -c 'echo "{ \"reference\": \"KDebugger.Plugins.Editor\" }" > "$0"' {} +

      - name: Replace Files without Editor
        run: |
          find . -type f -name 'ShizoGames.*.asmdef' -exec bash -c 'mv "$0" "${0/\.asmdef/.References.asmref}"' {} +
          find . -type f -name 'ShizoGames.*.References.asmref' -exec bash -c 'echo "{ \"reference\": \"KDebugger.Plugins\" }" > "$0"' {} +

      - name: Push Branch
        run: |
          git add .
          git commit -m "KDebugger Ready"
          git push origin kdbg
